Build using dakota 6.21 and boost 1.87
Patch dakota source directory_iterator
Remove seba and everest-models installation from local script
Remove hardcoded versions when looking for libraries

Have dakota install includes for eigen and nlohmann/json

Ref.
```
      include/dakota_data_io.hpp:22:10: fatal error: 'nlohmann/json.hpp' file not found
         22 | #include <nlohmann/json.hpp>
            |          ^~~~~~~~~~~~~~~~~~~
      5 warnings and 1 error generated.
      error: command '/usr/bin/clang++' failed with exit code 1
```

Add DAKOTA_SURROGATES python flag for cmake for local mac builds
Add python library to CMakeFiles patch
Build for specific os instead of ubuntu-latest
Still test with numpy 1.26.4
Added docker build script
Update supported python versions